### ISSUE TITLE
Blacklisting your own MAC addresses

### ISSUE THREAD

**Issue by saser** [cthit/hubbIT-old#113]
Since I do not use hubbIT myself, and do not want my computer (or phone) to be "tracked", I want to be able to blacklist its MAC address in order to prevent abuse (e.g. someone catching wind of my MAC address and adding it to their devices).

**Comment by Edholm** [comment]
Speak to someone in digIT and they will manually add your mac address to the blacklist.

**Comment by lindskogen** [comment]
Do as @Edholm says.
