### ISSUE TITLE
8-bIT not listed as a group

### ISSUE THREAD

**Issue by Fredokin** [cthit/hubbIT-old#118]
Noticed the Owe is listed correctly as both P.R.I.T. and DrawIT but not 8-bIT, which he should be listed as. Not sure if this is due to the group not being displayed in hubbIT or if the memberlist for 8-bIT is not up to date

**Comment by Vilddjur** [comment]
Can you check if this is still an issue, did some cache purging in our database.

**Comment by Fredokin** [comment]
Checked and it seems to have been resolved
