### ISSUE TITLE
Bad Scaling in Safari

### ISSUE THREAD

**Issue by Xiaoming94** [cthit/hubbIT-old#165]
Two IT-Students discovered the following scaling bug in safari:
![pasted image at 2017_04_07 14_40](https://cloud.githubusercontent.com/assets/6448975/24800453/8a5bbf2e-1ba0-11e7-90d9-2482e881a912.png)

And:

![17820145_10210291260372731_177853261_o](https://cloud.githubusercontent.com/assets/6448975/24800534/c5d8d438-1ba0-11e7-9880-3f4fd41b6b51.png)

**Comment by Levis92** [comment]
I think I've solved it. Will test it next time I'm in Hubben. Probably Sunday.
