### ISSUE TITLE
Missed case for default zero values

### ISSUE THREAD

**Issue by lindskogen** [cthit/hubbIT-old#167]
Error in `stats#show`:

![image](https://user-images.githubusercontent.com/817046/29355623-115b407a-8272-11e7-9479-e8f971feb36f.png)

Found the bug here: https://github.com/cthit/hubbIT/blob/develop/app/controllers/stats_controller.rb#L77-L83

`@session` can be present but `@sessions_within_timeframe` can be empty.
The values will be set to `nil` instead of zero since the else clause won't run.

**Comment by malmers** [comment]
Closed as of #169
