### ISSUE TITLE
Can't remove MAC address or go back 

### ISSUE THREAD

**Issue by Levis92** [cthit/hubbIT-old#199]
The remove buttons and back button has no effect when editing your devices. Tested i Chrome and Safari.

**Comment by lindskogen** [comment]
Probably a JS error, can you copy paste the output in the console?

**Comment by Levis92** [comment]
This is the only output I get and I get it when loading the page.
<img width="557" alt="screenshot 2019-01-30 09 08 12" src="https://user-images.githubusercontent.com/16805105/51967075-a5e8a300-246e-11e9-8bdb-71df4ad2b778.png">

**Comment by lindskogen** [comment]
Probably this file then: https://github.com/cthit/hubbIT/blob/c0e7fb6778fac0500d0b2f1bda32d691e47aa63b/app/assets/javascripts/cable/subscriptions/session.js.coffee

I'm not sure if we're using ActionCable anymore @malmers? Just remove/uncomment the file in that case.

**Comment by malmers** [comment]
I don't think so, remove it
