### ISSUE TITLE
Add scoreboards with time intervals

### ISSUE THREAD

**Issue by adamandreasson** [cthit/hubbIT-old#24]
Because the current "all-time" scoreboard is kind of unfair, I suggest adding different scoreboards based on the current week, month and läsperiod. Change the default scoreboard to something more  relevant, such as läsperiod.

:~]

**Comment by kimkling** [comment]
+1

**Comment by Edholm** [comment]
Study period isn't trivial to implement since it isn't all that easy to get the date when the study period starts and ends. The rest however should be bit av kaka.
