### ISSUE TITLE
Total time in The Hub differs between the stats page and the personal page

### ISSUE THREAD

**Issue by mhgbrg** [cthit/hubbIT-old#3]
At the moment of writing, Tejp has 149:18:45 on the stats page on https://hubbit.chalmers.it/stats, but on his personal page his total sum is 101:18:45. See pictures below. The same bug also seems to affect Horv's stats.

![image](https://cloud.githubusercontent.com/assets/1007436/9365552/78a43000-46b2-11e5-8a29-7daf07051f6b.png)

![image](https://cloud.githubusercontent.com/assets/1007436/9365591/a54ee794-46b2-11e5-8d73-3e97ad3a8301.png)

**Comment by Dr-Horv** [comment]
Resolved in #5
