### ISSUE TITLE
Link to user page is incorrect after logging in

### ISSUE THREAD

**Issue by malmers** [cthit/hubbIT-old#47]
'Me' in the navigation links to /users instead of /users/cid directly after logging in

**Comment by lindskogen** [comment]
This only makes things worse, instead of caching the value in the `@current_user` variable and returning it directly the next time, it now executes the method every time.

**Comment by Edholm** [comment]
This is probably related to the _"You don't seem to have any MAC-addresses defined, go to your user page and add some!"_

**Comment by lindskogen** [comment]
Absolutely, for some reason, the user is not fetched correctly, possibly the `session` variable has something to do with this
