### ISSUE TITLE
Make it possible to select what date interval is shown in time graph and stats

### ISSUE THREAD

**Issue by Criticalstone** [cthit/hubbIT-old#60]

**Comment by Dr-Horv** [comment]
We should at least make days/weeks/months pagianted so users can switch between them.

**Comment by Edholm** [comment]
@Dr-Horv How do you mean?

**Comment by Dr-Horv** [comment]
@Edholm At the moment only current month can be viewed for example. I can't find out the stats for last month. Would be nice ot have a "prev"-button to change view between months, weeks, days etc.

**Comment by Edholm** [comment]
ah now I get it. Wouldn't be that hard to fix.

**Comment by Dr-Horv** [comment]
@Edholm Indeed, would be nice feature to have. :) Win-win
