### ISSUE TITLE
User tips for hubbIT

### ISSUE THREAD

**Issue by lindskogen** [cthit/hubbIT-old#61]
```
16:17 <Ndushi> *någon* kanske borde samla ihop lite "tips" för hubbit
16:17 <Ndushi> vart man hittar mac-adresser för android och iOS
16:17 <Ndushi> att man kan kopiera den genom att hålla ner (på iOS iaf)
16:18 <Ndushi> att man skall slå på "keep wifi on in sleep mode" på android
16:19 <Horv> 
```

![](http://i.imgur.com/2WfGKSS.png)

**Comment by Cannonbait** [comment]
Sounds good, something to be added to a tutorial section to make it easier for people to register, it's not blatantly obvious to all how you find your MAC-addresses. And we do like blatantly obvious

**Comment by lindskogen** [comment]
@Edholm is great at documenting stuff, go ahead!

**Comment by Edholm** [comment]
See pull request #126
