### ISSUE TITLE
Make groups only "sittande"

### ISSUE THREAD

**Issue by ErikKarlkvist** [cthit/hubbIT-old#65]
Read title
//Tuna

**Comment by Edholm** [comment]
This is related to how groups are structured in our LDAP. Removing "old people" will remove their access to certain services such as the wiki.

A new structure is on its way that will solve this.

 [EDIT] This will also introduce "patet" groups, such as didIT and exIT

**Comment by Edholm** [comment]
I have removed group stats in f853eb1413f6232713e22ab59cc79acaf576e227 until this is fixed. Closing...
