### ISSUE TITLE
Change from mdl-lite to Foundation

### ISSUE THREAD

**Issue by Edholm** [cthit/hubbIT-old#71]
Since the rest of our sites uses Foundation. Keep consistency

**Comment by Dr-Horv** [comment]
I agree that consistency would be nice. I think I rather convert the rest to material design though. :smile:

**Comment by Edholm** [comment]
That is a massive job. Also, foundation is a much nicer framework

**Comment by Dr-Horv** [comment]
@Edholm Hehe, I know. It was not such a serious note. I don't really like the look and feel of Foundation personally though.

**Comment by Edholm** [comment]
ah ok. The grid systems is really really nice though!

**Comment by lindskogen** [comment]
Solved after redesign
