### ISSUE TITLE
Intruders in the hubb

### ISSUE THREAD

**Issue by SamuelHakansson** [cthit/hubbIT-old#76]
The "There are 9 smurfs in the Hubb right now!" could be enhanced to "There are 9 smurfs and 3 intruders in the Hubb right now!". Every device which hasn't registred its mac-address is an intruder.

**Comment by lindskogen** [comment]
I think the main problem is regarding the personal privacy concern, the only mac addresses we track currently are the ones where people have given their consent to let us save their activity.

**Comment by Edholm** [comment]
Also, this would pick up many people in Kajsa baren (and people walking outside) and would therefore give an inaccurate picture.
