### ISSUE TITLE
Sniffer does not start @ system boot

### ISSUE THREAD

**Issue by vidare** [cthit/hubbIT-old#83]
When the bardatorn is restarted or otherwise forced to boot digIT has to manually start the sniffer script. This results in unnecessary downtime.

**Comment by Dr-Horv** [comment]
@abjugard You fixed thsi right?

**Comment by lindskogen** [comment]
@abjugard update?

**Comment by abjugard** [comment]
I believe so, either way next LTS of Ubuntu will enable the use of systemd services so any further work on this issue will have to wait until the release of that. Also this issue really should be filed on the [hubbIT-sniffer](../../hubbIT-sniffer) repo rather than on hubbIT.

**Comment by Vilddjur** [comment]
closed by https://github.com/cthit/hubbIT-sniffer/commit/f62c14b4a71fa14040d1c4e3f4b21cc35bcff0a3
